### ISSUE TITLE
tags is not defined

### ISSUE THREAD

**Issue by jzrskc** [mufidu/pocket-to-markdown#1]
I often get this error, and it works when this part of code is deleted/commented:

```
ReferenceError: tags is not defined
    at file:///{{userLocation}}/pocket-to-markdown/singleWeb.js:26:5
```

**Comment by mufidu** [comment]
Oops, yeah URL imported with `singleWeb.js` shouldnt have tags anyway. Should be fixed now. Thanks for reporting!
